# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Lucky's Slice Of The Internet"

# A description of your site for social meta tag, search engines, and feed.xml
description: "A little bit of everything"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://luckysmith.dev"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: about.md
- text: Portfolio
  url: Portfolio.md
- text: Archives
  url: /tags/


# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Author information - author info at the bottom of the post
author_name: "Lucky Smith"
author_bio: "IT Professional, Web developer, Computer Tinkerer, Star Wars fan"
author_url:  "http://lcmsmith.com"
author_location: "United States"
author_image: /assets/images/authorimage.png

# Social links in the site footer
github_username: "luckycoder1030"


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'
plugins: [jekyll-paginate]

# Permalinks
permalink: /:title

markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
